### ISSUE TITLE
Telefone celular não aceita número valido

### ISSUE THREAD

**Issue by kevin74Unifei** [rodrigoaasm/sissarproject#3]
O campo telefone celular no cadastro de funcionários, não está permitindo o cadastro de telefones, informando que o telefone deve estar no formato exigido, mesmo quando o telefone está correto; implicando assim que não é possível concluir o cadastro de um funcionário.

**Comment by rodrigoaasm** [comment]
No atributo ‘pattern’ do input havia um espaço a mais entre o DDD e o telefone. Foi Corrigido.
