### ISSUE TITLE
Possível erro em rota

### ISSUE THREAD

**Issue by LucasLamounierD** [rodrigoaasm/sissarproject#5]
Ao clicar no icone usuario de um perfil ja cadastrado:

- Ao confirmar os dados ele te redireciona para uma página em que todo conteudo fica desformatado.

![captura de tela de 2017-05-29 14-10-48](https://cloud.githubusercontent.com/assets/28604186/26557745/f8418f76-4479-11e7-9beb-3a78ee6cb2c0.png)

- Todos os usuario independente de como foram cadastrados na opção usuario sempre aparece "Candidato" no menu de escolha do perfil de usuario.

![captura de tela de 2017-05-29 14-21-37](https://cloud.githubusercontent.com/assets/28604186/26557776/36bab9c6-447a-11e7-87ed-3033b1a17622.png)

**Comment by rodrigoaasm** [comment]
Divida os dois problemas em dois issues, o primeiro é uma pagina apenas para auxilio do desenvolvedor, já que não existirá no sistema uma ferramenta que  exiba uma lista de usuarios. 
O segundo faça um no issues. Para organização!
